#!/usr/bin/env python3

import i3ipc

# Create the Connection object that can be used to send commands and subscribe
# to events.
i3 = i3ipc.Connection()
coloractive = '%{U#eeeeee}'
colorinactive = '%{U#9eb2cb}'
colorwarning = '%{U#e84f4f}'

# Define a callback to be called when you switch workspaces.
def on_workspace_focus(self, e):
    workspace_string = '    '
    workspaces = i3.get_workspaces()

    ws_nums = [int(n['num']) for n in workspaces]
    focused = [n['visible'] for n in workspaces].index(True)
    urg = [n for n, _ in enumerate(workspaces) if workspaces[n]['urgent'] == True]
    names =[''.join([i for i in n['name'] if not i.isdigit()]) for n in workspaces]

    for n in range(len(ws_nums)):
        if focused == n:
            workspace_string += coloractive + "%{+u}  " + str(ws_nums[n]) + "  %{-u}%{U-}" + '  '
        elif n in urg:
            workspace_string += colorwarning + "%{+u}  " + str(ws_nums[n]) + "  %{-u}%{U-}" + '  '
        else:
            workspace_string += colorinactive + "%{+u}  " + str(ws_nums[n]) + "  %{-u}%{U-}" + '  '

    print(workspace_string, flush=True)

# Subscribe to events
i3.on('workspace', on_workspace_focus)
on_workspace_focus(0, 0)

# Start the main loop and wait for events to come in.
i3.main()
