#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
opt=0


title=Password
prefix=${PASSWORD_STORE_DIR-~/.password-store}

while getopts "to" opt; do
    case "$1" in
    -t)
        typeit=1
        ;;
    -o)
        otp=1
				title=OTP
				subfolder=/.otp
        ;;
    esac
done


password_files=( "$prefix$subfolder"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )


if [ -z $WAYLAND_DISPLAY ]; then
  echo "using rofi to show"
  password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu  -window-title $title -i "$@")
else 
  echo "using wofi to show"
  password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu  -window-title $title -i "$@")
fi

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
		if [[ $otp -eq 0 ]]; then
    	echo "copy password"
	  	pass -c "$password" 
		else 
    	echo "copy otp"
	  	pass otp -c "$password" 
		fi
else
  if [ -z $WAYLAND_DISPLAY ]; then
    echo "using Xorg copy mechanism"

		if [[ $otp -eq 0 ]]; then
    	echo "copy password"
	  	pass -c "$password" 
		else 
    	echo "copy otp"
	  	pass otp -c "$password" 
		fi
  else 
    echo "using wayland copy mechanism"
		if [[ $otp -eq 0 ]]; then
    	echo "copy password"
	  	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | wl-copy
		else 
    	echo "copy otp"
	  	pass opt show "$password" | { IFS= read -r pass; printf %s "$pass"; } | wl-copy
		fi
  fi
fi


