#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )


if [ -z $WAYLAND_DISPLAY ]; then
  echo "using rofi to show"
  password=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu -i "$@")
else 
  echo "using wofi to show"
  password=$(printf '%s\n' "${password_files[@]}" | wofi --dmenu -i "$@")
fi

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
	pass show -c "$password" 2>/dev/null
else
  if [ -z $WAYLAND_DISPLAY ]; then
    echo "using Xorg copy mechanism"
	  pass -c "$password" 
  else 
    echo "using wayland copy mechanism"
	  pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | wl-copy
  fi
fi
