#!/bin/bash

echo "starting post-new…"

export start=""


# Spam detection, enable if ready
# for mid in $(notmuch search --output=messages tag:new); do
#     if notmuch show --format=raw "$mid" 2>/dev/null | awk '!NF{exit 1} /^X-Spam_bar: \+\+\+\+\+\+\+\+/ {exit 0}'; then
#     notmuch tag -new +spam "$mid"
#     fi
# done

# Prüfe ob es neue Emails gibt. Wird später für die Benachrichtigung gebraucht
newCounter="$(notmuch count tag:new)"

# retag wrong tagged tags (comment in)
#notmuch tag -inbox -gmail -gmx -photography -work -sent +new -- 

# retag all "new" messages "inbox" and "unread"
notmuch tag +inbox -new -- tag:new

# tag all messages from "me" as sent and remove tags inbox and unread
notmuch tag -new -inbox +sent -- from:svzieg@gmx.de or from:sven.ziegler@scheer-group.com or from:sven.ziegler@svenziegler.photography or from:ziggo1879@gmail.com
# tag newsletters, but dont show them in inbox
notmuch tag +newsletters -new -- from:newsletter@example.org or subject:'newsletter*'


# add receiver tag
notmuch tag +gmail --        tag:inbox and to:ziggo1879@gmail.com
notmuch tag +gmx --          tag:inbox and to:svzieg@gmx.de
notmuch tag +photography --  tag:inbox and to:sven.ziegler@svenziegler.photography
notmuch tag +work --         tag:inbox and to:sven.ziegler@scheer-group.com

if [ "$newCounter" != "0" ]; then
  notify-send "`$newCounter` Mails arrived"  
fi

echo "post-new complete; goodbye"
