#!/bin/bash

echo "starting post-new…"

export start=""


# Spam detection, enable if ready
 for mid in $(notmuch search --output=messages tag:new); do
     if notmuch show --format=raw "$mid" 2>/dev/null | awk '!NF{exit 1} /^X-Spam_bar: \+\+\+\+\+\+\+\+/ {exit 0}'; then
     notmuch tag -new +spam "$mid"
     fi
 done




# Prüfe ob es neue Emails gibt. Wird später für die Benachrichtigung gebraucht
newCounter="$(notmuch count tag:new)"

# retag wrong tagged tags (comment in)
#notmuch tag -inbox -gmail -gmx -photography -work -sent +new -- 


## notmuch tag -inbox -new +spam -- tag:new and folder:".*(s|S)pam.*"
notmuch tag -inbox -new +spam -- tag:new and X-Spam_bar:" "

# tag all messages from "me" as sent and remove tags inbox and unread
notmuch tag -new -inbox +sent -- tag:new and from:svzieg@gmx.de or from:sven.ziegler@scheer-group.com or from:sven.ziegler@svenziegler.photography or from:ziggo1879@gmail.com
# tag newsletters, but dont show them in inbox
# notmuch tag +newsletters -new -- from:newsletter@example.org or subject:'newsletter*'

# retag all "new" messages "inbox" and "unread"
notmuch tag +inbox -- tag:new
notmuch tag -inbox +newsletter -- to:ziggo1879+newsletter@gmail.com and not tag:newsletters
notmuch tag -inbox +spam -- to:ziggo1879+gewinn@gmail.com and not tag:spam

notmuch tag -inbox +archlinux +maillist -- from:arch-general-request@archlinux.org or from:arch-events-request@archlinux.org or from:arch-announce-request@archlinux.org and not tag:maillist
notmuch tag -inbox +archlinux +maillist -- from:arch-general@archlinux.org or from:arch-events@archlinux.org or from:arch-announce@archlinux.org and not tag:maillist

# add receiver tag
notmuch tag +gmail --        tag:new and to:ziggo1879@gmail.com and not tag:gmail
notmuch tag +gmx --          tag:new and to:svzieg@gmx.de and not tag:gmx
notmuch tag +photography --  tag:new and to:sven.ziegler@svenziegler.photography and not tag:photography
notmuch tag +work --         tag:new and to:sven.ziegler@scheer-group.com and not tag:work

# add wiki, bugtracker tag
notmuch tag +wiki --         tag:new and tag:work and from:wiki@e2ebridge.com and not tag:wiki
notmuch tag +jira --         tag:new and tag:work and from:issues@e2ebridge.com and not tag:jira
notmuch tag +bpaas --        tag:new and tag:work and subject:".*(?i)bpaas.*" and not tag:bpaas

notmuch tag +robot --         tag:new and tag:work and from:"rpa.*"
notmuch tag +robot --         from:"rpa*@egetrans.com" and tag:work and not tag:robot
notmuch tag +robot --         from:"belegroboter@lgi.de" and tag:work and not tag:robot

# delete all new tags
notmuch tag -new -- tag:new

if [ "$newCounter" != "0" ]; then
  dunstify "`$newCounter` Mails arrived"  
fi

echo "post-new complete; goodbye"
