#!/bin/bash

echo "starting post-new…"

export start=""


for mid in $(notmuch search --output=messages tag:new); do
    if notmuch show --format=raw "$mid" 2>/dev/null | awk '!NF{exit 1} /^X-Spam_bar: \+\+\+\+\+\+\+\+/ {exit 0}'; then
    notmuch tag -new +spam "$mid"
    fi
done



newCounter="$(notmuch count tag:new)"

if [ "$newCounter" != "0" ]; then
  notify-send "`$newCounter` Mails arrived"  
fi



# retag all "new" messages "inbox" and "unread"
notmuch tag +inbox -new -- tag:new


# retag wrong tagged tags (comment in)
# notmuch tag -inbox -unread -sent +new -- tag:sent

# tag all messages from "me" as sent and remove tags inbox and unread
notmuch tag -new -inbox +sent -- from:svzieg@gmx.de or from:sven.ziegler@scheer-group.com or from:sven.ziegler@svenziegler.photography or from:ziggo1879@gmail.com
# tag newsletters, but dont show them in inbox
notmuch tag +newsletters -new -- from:newsletter@example.org or subject:'newsletter*'



echo "post-new complete; goodbye"
