# Shell variables
# Generated by 'wal'
wallpaper='/home/svzieg/.config/sway/wallpaper/dust-storm.jpg'

# Special
background='#1c1916'
foreground='#c6c5c4'
cursor='#c6c5c4'

# Colors
color0='#1c1916'
color1='#785129'
color2='#9d6d3d'
color3='#aa875e'
color4='#c08548'
color5='#ca9c66'
color6='#e0bd8b'
color7='#c6c5c4'
color8='#545250'
color9='#785129'
color10='#9d6d3d'
color11='#aa875e'
color12='#c08548'
color13='#ca9c66'
color14='#e0bd8b'
color15='#c6c5c4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
