# Shell variables
# Generated by 'wal'
wallpaper='/home/svzieg/Downloads/arc-darker.png'

# Special
background='#191c23'
foreground='#c7d6e7'
cursor='#c7d6e7'

# Colors
color0='#191c23'
color1='#657C94'
color2='#6F949A'
color3='#5295E3'
color4='#6BA2E3'
color5='#939CA0'
color6='#8BABAC'
color7='#c7d6e7'
color8='#8b95a1'
color9='#657C94'
color10='#6F949A'
color11='#5295E3'
color12='#6BA2E3'
color13='#939CA0'
color14='#8BABAC'
color15='#c7d6e7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
